[package]
name = "aabb_occlusion_culling"
version = "0.1.0"
edition = "2021"


[lib]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
box_intersect_ze = {path="../box_intersect_ze"}
plotters = "0.3.4"
stdext = "0.3.1"

